layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"
      
resume:
  education:
    - organization: Duke University
      position: Computer Science
      date: Class of 2022
      location: Durham, NC

projects:
  featured:
    - jbonner50/python-project-collection
    - jbonner50/python-data-vis-tutorial
    - jbonner50/hello-world
  exclude:
    archived: true
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  instagram: jbonner_50
  # keybase: your_username
  linkedin: jeff-bonner-37b8b5167
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  youtube: channel/UCWUGc092GG4i0I-rr6gmJcg
  email: jbonner50@gmail.com

topics:
  - name: Dart
    web_url: https://dart.dev
    image_url: https://raw.githubusercontent.com/jbonner50/jbonner50.github.io/master/assets/logo_dart_1080px_clr.png
  - name: Flutter
    web_url: https://flutter.dev
    image_url: https://raw.githubusercontent.com/jbonner50/jbonner50.github.io/master/assets/logo_flutter_1080px_clr.png
  - name: Python
    web_url: https://www.python.org
    image_url: https://raw.githubusercontent.com/jbonner50/jbonner50.github.io/master/assets/1024px-Python-logo-notext.png
  - name: Raspberry Pi
    web_url: https://www.raspberrypi.org
    image_url: https://raw.githubusercontent.com/jbonner50/jbonner50.github.io/master/assets/Raspi-PGB001.png